// Cloudflare Worker entrypoint — wraps the OpenNext-built Worker to add a
// `scheduled()` handler so cron triggers can drive the queue processor.
//
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and
// only exports `fetch` + Durable Object classes. We re-export everything it
// exposes, then attach our own scheduled handler that constructs a synthetic
// internal Request to /api/cron/process-queue with the `x-cron-secret` header
// (route handler validates it via env.CRON_SECRET).

import openNextWorker, * as openNextExports from './.open-next/worker.js'

// Re-export all named exports (Durable Object classes etc.) unchanged.
export const DOQueueHandler = openNextExports.DOQueueHandler
export const DOShardedTagCache = openNextExports.DOShardedTagCache
export const BucketCachePurge = openNextExports.BucketCachePurge

export default {
  fetch(request, env, ctx) {
    return openNextWorker.fetch(request, env, ctx)
  },

  async scheduled(event, env, ctx) {
    if (!env.CRON_SECRET) {
      console.error('[cron] CRON_SECRET not set, skipping')
      return
    }
    const url = 'https://internal.cron/api/cron/process-queue'
    const req = new Request(url, {
      method: 'POST',
      headers: { 'x-cron-secret': env.CRON_SECRET },
    })
    try {
      const res = await openNextWorker.fetch(req, env, ctx)
      const body = await res.text()
      console.log(`[cron ${event.cron}] process-queue ${res.status} ${body}`)
    } catch (err) {
      console.error(`[cron ${event.cron}] error:`, err)
    }
  },
}
