// Cloudflare Worker entrypoint — wraps the OpenNext-built Worker to add a
// `scheduled()` handler so cron triggers can drive multiple internal endpoints.
//
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and
// only exports `fetch` + Durable Object classes. We re-export everything it
// exposes, then attach our own scheduled handler that synthesizes internal
// Requests with the `x-cron-secret` header (route handlers validate it via
// env.CRON_SECRET).
//
// Cron routing (matches wrangler.toml [triggers]):
//   */5 * * * * → /api/cron/process-queue       (drain queued notifications)
//   0 5 * * *   → /api/cron/deadline-scheduler  (daily, 05:00 UTC = 08:00 Bucharest)

import openNextWorker, * as openNextExports from './.open-next/worker.js'

export const DOQueueHandler = openNextExports.DOQueueHandler
export const DOShardedTagCache = openNextExports.DOShardedTagCache
export const BucketCachePurge = openNextExports.BucketCachePurge

const CRON_ROUTES = {
  '*/5 * * * *': '/api/cron/process-queue',
  '0 5 * * *': '/api/cron/deadline-scheduler',
}

async function callCronEndpoint(env, ctx, path, label) {
  const url = `https://internal.cron${path}`
  const req = new Request(url, {
    method: 'POST',
    headers: { 'x-cron-secret': env.CRON_SECRET },
  })
  try {
    const res = await openNextWorker.fetch(req, env, ctx)
    const body = await res.text()
    console.log(`[cron ${label}] ${path} ${res.status} ${body}`)
  } catch (err) {
    console.error(`[cron ${label}] error:`, err)
  }
}

export default {
  fetch(request, env, ctx) {
    return openNextWorker.fetch(request, env, ctx)
  },

  async scheduled(event, env, ctx) {
    if (!env.CRON_SECRET) {
      console.error('[cron] CRON_SECRET not set, skipping')
      return
    }
    const path = CRON_ROUTES[event.cron]
    if (!path) {
      console.error(`[cron] no route for schedule "${event.cron}"`)
      return
    }
    await callCronEndpoint(env, ctx, path, event.cron)
  },
}
