// One-shot builder for the embedded PDF wordmark.
//
// pdf-lib doesn't support SVG embedding, and Cloudflare Workers have no `fs`,
// so we rasterise public/logo-wordmark.svg to a PNG and base64-encode it into
// a TypeScript constant. The constant is then bundled with the Worker like
// any other JS string. That avoids:
//   - runtime SVG → PNG conversion cost in the request hot path
//   - fetching the PNG over HTTP from the Worker back to itself
//   - shipping a separate bundling pipeline for binary asset imports
//
// Run when the source SVG changes:
//   npx tsx scripts/build-wordmark-asset.ts
//
// Output dimensions are 3× the largest in-PDF embed size (cover at ~120pt
// wide → 360pt at 3× → 480px nominal) so the rasterised wordmark stays crisp
// at zoom in PDF viewers without inflating bundle size unnecessarily.

import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import sharp from 'sharp'

const SVG_PATH = resolve('public/logo-wordmark.svg')
const TS_OUTPUT = resolve('lib/rate-cards/wordmark-asset.ts')
// Width 720 px → at 3× the cover embed (~120pt × 3 = 360pt = ~480 px) plus
// some headroom. Aspect of the source SVG is ~11.91 : 1, height computed.
const TARGET_WIDTH = 720

async function main() {
  const svg = await readFile(SVG_PATH)
  const meta = await sharp(svg).metadata()
  if (!meta.width || !meta.height) {
    throw new Error('Could not read SVG metadata')
  }
  const aspect = meta.width / meta.height
  const targetHeight = Math.round(TARGET_WIDTH / aspect)

  const png = await sharp(svg, { density: 600 })
    .resize({ width: TARGET_WIDTH, height: targetHeight })
    .png({ compressionLevel: 9, palette: true })
    .toBuffer()

  const base64 = png.toString('base64')

  const ts = `// Auto-generated by scripts/build-wordmark-asset.ts — do NOT edit.
// Source: public/logo-wordmark.svg (rasterised at ${TARGET_WIDTH}×${targetHeight}px).
// Aspect ratio: ${aspect.toFixed(4)}.
//
// Re-run \`npx tsx scripts/build-wordmark-asset.ts\` when the source SVG
// changes. PDF generator reads this constant via decodeWordmarkPng() in
// pdf-generator.ts.

export const WORDMARK_PNG_WIDTH = ${TARGET_WIDTH}
export const WORDMARK_PNG_HEIGHT = ${targetHeight}
export const WORDMARK_ASPECT_RATIO = ${aspect.toFixed(4)}

export const WORDMARK_PNG_BASE64 =
  '${base64}'
`
  await writeFile(TS_OUTPUT, ts)
  console.log(`SVG metadata:    ${meta.width} × ${meta.height} (aspect ${aspect.toFixed(4)})`)
  console.log(`PNG dimensions:  ${TARGET_WIDTH} × ${targetHeight}`)
  console.log(`PNG bytes:       ${png.length}`)
  console.log(`base64 length:   ${base64.length}`)
  console.log(`Wrote:           ${TS_OUTPUT}`)
}

void main()
